### PR TITLE
Added EF Core support

### PR DESCRIPTION
**Pull request by dariogriffo**

### CODE REVIEW

**Comment by dariogriffo** [comment]
This doesn't compile because the folder structure of the the upstream is not ideal to work in .net.
Different projects should live in different folders.

**Comment by medo64** [comment]
No worries. I'll pull it in and play with conditionals a bit. I might ping you later to check as I don't have EF setup here.

**Comment by dariogriffo** [comment]
> No worries. I'll pull it in and play with conditionals a bit. I might ping you later to check as I don't have EF setup here.

It's ok, you don't need anything.
The tests are using SQLite and the files are created and deleted on every run.
You just need to sort out the projects and file structure

**Comment by medo64** [comment]
Of course I messed up the pull - got into main... :)
Will fix it in the next hour or so.

**Comment by dariogriffo** [comment]
You can use conditional includes in the csproj
<PropertyGroup>
  <DefaultItemExcludes>$(DefaultItemExcludes);TheOtherProject.csproj;*Converter.cs</DefaultItemExcludes>
</PropertyGroup>

**Comment by medo64** [comment]
Ok, now it should all compile.
Can you please check?

**Comment by medo64** [comment]
I will sort out make script in meantime. Also, please note that XML comments are missing on Uuid7To*Converter classes. Can you add them in another pull request?

**Pull request merged**
